-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.backers_df;

CREATE TABLE IF NOT EXISTS public.backers_df
(
    backer_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    cf_id integer NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_backers_df PRIMARY KEY (backer_id)
);

DROP TABLE IF EXISTS public.campaign;

CREATE TABLE IF NOT EXISTS public.campaign
(
    cf_id integer NOT NULL,
    contact_id integer NOT NULL,
    company_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    goal numeric(10, 2) NOT NULL,
    pledge numeric(10, 2) NOT NULL,
    outcome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    backers_count integer NOT NULL,
    country character varying(10) COLLATE pg_catalog."default" NOT NULL,
    currency character varying(10) COLLATE pg_catalog."default" NOT NULL,
    launch_date date NOT NULL,
    end_date date NOT NULL,
    category_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    subcategory_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_campaign PRIMARY KEY (cf_id)
);

DROP TABLE IF EXISTS public.category;

CREATE TABLE IF NOT EXISTS public.category
(
    category_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    category_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (category_id)
);

DROP TABLE IF EXISTS public.contacts;

CREATE TABLE IF NOT EXISTS public.contacts
(
    contact_id integer NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_contacts PRIMARY KEY (contact_id)
);

DROP TABLE IF EXISTS public.subcategory;

CREATE TABLE IF NOT EXISTS public.subcategory
(
    subcategory_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    subcategory_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_subcategory PRIMARY KEY (subcategory_id)
);

ALTER TABLE IF EXISTS public.backers_df
    ADD CONSTRAINT fk_backers_df_cf_id FOREIGN KEY (cf_id)
    REFERENCES public.campaign (cf_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.campaign
    ADD CONSTRAINT fk_campaign_category_id FOREIGN KEY (category_id)
    REFERENCES public.category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.campaign
    ADD CONSTRAINT fk_campaign_contact_id FOREIGN KEY (contact_id)
    REFERENCES public.contacts (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.campaign
    ADD CONSTRAINT fk_campaign_subcategory_id FOREIGN KEY (subcategory_id)
    REFERENCES public.subcategory (subcategory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;